### ISSUE TITLE
create mardi_importer namespace for python modules

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/docker-importer#10]
Currently, the python package is called "mardi_importer" and includes the packages "zbmath", "wikidata", etc, which can be imported via `import zbmath`, etc.
It seems cleaner to bundle these modules into an "umbrella" module, i.e., folder structure
```
docker-importer/
    src/
        mardi_importer/
            __init__.py
            zbmath/
            wikidata/
            ...
```
such that the imports work via `from mardi_importer import zbmath`.

 
**TODOS**: 
- [ ] create folder
- [ ] adapt all imports in the py files to new structure

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
