### ISSUE TITLE
zbMATH Open Todo

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/docker-importer#108]
- [x] complete first import
- [ ] check that all papers are there
    - [ ] delete and re-upload papers with several zbmath-ids
    - [ ] check and retry papers that are not there right now 
- [ ] disambiguate authors
    - [x] merge the ones with the same zbmath id
    - [ ] query other identifiers from wikidata and merge on them 
- [ ] include references
- [ ] scrape paper and author names
- [ ] think about how to handle updates in zbmath
- [ ] rewrite code to work with Airflow
- [ ] pull new stuff

**Comment by eloiferrer** [comment]
Once the first round of author disambiguation is finished, I think it would be interesting to add the ORCID info from here:
https://zenodo.org/records/7378860

And maybe also the DOI for articles (I am not sure if that is there already for all articles).

**Comment by eloiferrer** [comment]
There are 44 authors with zbMath ID = None. Maybe we can correct this manually.

http://tinyurl.com/yljpyws3

**Comment by eloiferrer** [comment]
This query returns publications that have two DOIs: http://tinyurl.com/22huojf5
Most of the cases seems to be two different articles (with same title) that have been written in the same item.

**Comment by physikerwelt** [comment]
@LizzAlice is this still relevant/ up to date?

**Comment by LizzAlice** [comment]
No, not anymore, I just forgot to close/update
