### ISSUE TITLE
Replace merged QIDs in statements

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#109]
**Issue description**:
When an item is merged into another item there is a redirection from the old item page to the new one.
However, the statements in other items that point to the old item QID are not updated.
This is problematic. For instance publications that are attributed to an author using an old QID (before being merged) will not show up in the profile page of the author after the merge.
We need a bot job that updates all the statements of items that have been merged and substitutes the old ID by the new ID. 
 
**TODOS**: 
- [ ] Get a list of all items that have been merged
- [ ] Look for all the statements where the old QID appears
- [ ] Update the statements

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
This is solved by the RedirectionBot.
