### ISSUE TITLE
Fix arXiv/zbMath overlap

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#121]
**Issue description**:
Some publications were first created by the CRAN importer and later overwritten by the zbMath importer.
This resulted in single items that merge the metadata from the arXiv preprint with the metadata from the published article in a journal coming from zbMath.
For these cases we have two DOIs, duplicate authors and potentially other problems.
Some of the items affected can be found here: http://tinyurl.com/22huojf5
 
 
**TODOS**: 
- [ ] Identify items affected by this
- [ ] Get the zbMath ID for each of this articles
- [ ] Reverse the last edit made the zbMath importer to restore the original version
- [ ] Create a separate item with the zbMath id.

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
Overwrite has been reversed and the zbMath items created as separate items.
