### ISSUE TITLE
Add deprecation qualifiers for CRAN

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#122]
**Issue description**:
There is no indication for deprecated R packages in the KG.
 
 
**TODOS**: 
- [ ] For all deprecated packages add qualifier 'End Time' (https://www.wikidata.org/wiki/Property:P582) to the CRAN Project (https://www.wikidata.org/wiki/Property:P5565) statement.

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.
