### ISSUE TITLE
Add software profile statements for R packages

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#123]
**Issue description**:
All CRAN packages must have a statement using https://portal.mardi4nfdi.de/wiki/Item:Q5976447 to allow the creation of Software profile pages. 
 
 
**TODOS**: 
- [x] Create MaRDI software profile item mirroring https://portal.mardi4nfdi.de/wiki/Item:Q5976445
- [x] Add statement to each CRAN package

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.
