### ISSUE TITLE
Consolidate P1457 and P1459

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#137]
**Issue description**:
Two 'description' properties where created due to the label being manually changed.
All items should just use the same property and the redundant one has to be deleted. 
 
**TODOS**: 

- [x] Update all items here: https://tinyurl.com/2cd2fou8 to use P1459
- [x] Update templates that use P1457
- [x] Delete property P1457

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.
