### ISSUE TITLE
Merge duplicated publications

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#139]
**Issue description**:
After inserting the arXiv id in zbMath publications, it is possible now to identify several duplicated publication items.
See: https://tinyurl.com/272j99ec
Just merging these items will result in most of the merged items having duplicated authors. These repeated authors will also have to be merged.
 
**TODOS**: 
- [ ] Merge duplicated items (+ delete linked publication pages)
- [ ] Merge duplicated authors

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.
