### ISSUE TITLE
Create regular user in docker container

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/docker-importer#24]
The docker container uses root. It seems cleaner to create a regular user in the Dockerfile.

Note that this might interfere with #23 (`pip install --user -e .`)

**Checklist for this issue**: 
(Some checks for making sure this feature-request is completely formulated)
- [ ] Participants in discussion have been invited as assignees 
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] MaRDI_Project has been assigned as project

**Comment by physikerwelt** [comment]
@LizzAlice are you still working on this, or can this be closed?

**Comment by LizzAlice** [comment]
I pushed that one back because it was rather difficult to solve.

**Comment by physikerwelt** [comment]
If it is difficult and not important, I suggest closing the issue. I think it is not foreseeable until the end of the project, that there is time to make cosmetic changes.
