### ISSUE TITLE
[Epic] Import properties from Wikibase that are relevant

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/docker-importer#4]
- [x] Investigate tools. https://www.mediawiki.org/wiki/Wikibase/Importing
- [x] Implement the [chosen tool](https://github.com/MaRDI4NFDI/WikibaseImport) in a [container](https://github.com/MaRDI4NFDI/docker-importer)
- [x] #19
- [ ] Check if  all relevant scripts from Jupyter Notebooks have been implemented in Docker-Importer. 
- [x] #18
- [ ] Check if Wikibase Importer is sufficient for future since it seems to be not well maintained.

**Comment by eloiferrer** [comment]
The import of Wikibase items & properties has been implemented using WikibaseIntegrator.
* Imported Properties are assigned the Wikidata PID property (https://portal.mardi4nfdi.de/wiki/Property:P11) to link to the original Wikidata ID.
* Imported Items are assigned the Wikidata QID property (https://portal.mardi4nfdi.de/wiki/Property:P12) to link to the original Wikidata ID.
