### ISSUE TITLE
Import swMath software information

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/docker-importer#5]
**Issue description**:

 
 
**TODOS**: 

- [ ] example todo to copy 

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
