### ISSUE TITLE
Automatic creation of Bot for import

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/docker-importer#52]
Look into automatic bot creation for the importer; alternatively get import to work without Bot
  
 
 
**TODOS**: 
(In technical terms suggestions what has to be done to implement the feature.) 
-  
-  
- 

**Considered Alternatives**: 
(Alternatives which have been considered for this feature) 
- 

**Checklist for this issue**: 
(Some checks for making sure this feature-request is completely formulated)
- [ ] Participants in discussion have been invited as assignees 
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] MaRDI_Project has been assigned as project

**Comment by Hyper-Node** [comment]
Could you add no-epic tag or add this to an epic, so it can be tracked ?
