### ISSUE TITLE
[Epic] Integrate TA4 workflows into the portal

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#63]
**Epic description in words**:
TA4 workflows are generated as markdown files. 
The objective is to process these workflows and based on them create wikibase entities and mediawiki pages.
Once the workflow info is in the portal based (entities and pages exist), search functionality for existing workflows should be optimized.

 
**TODOS**: 
- [ ] #64
- [ ] #65
- [ ] #66
- [ ] Create mediawiki page based on the info that has been inserted into wikibase and on the workflow template.
- [ ] Predefine SPARQL queries to explore/visualize the imported workflows.

**Related bugs**: 
  
- 

**Epic acceptance criteria**: 
  
- [ ] first criterion 

**Checklist for this epic**: 
- [ ] the main MaRDI project has been assigned as project
- [ ] report has been created

**Comment by eloiferrer** [comment]
This epic has been superseded by a more general solution to insert data into Wikibase, which shall support also other TAs. See https://github.com/MaRDI4NFDI/portal-compose/issues/339
