### ISSUE TITLE
Import polyDB metadata

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#71]
**New feature description in words**:
Import polyDB metadata (polydb.org) into the knowledge graph.  
 
 
**TODOS**: 
- Import metadata through the Rest API (https://polymake.org/polytopes/paffenholz/polyDB-rest.html)
- Clean metadata (disambiguate authors through ORCID, retrieve DOIs for publications)
- Define new properties and items (polyDB collection, contributed by)
- Import supporting entities from Wikidata
- Create entities in the KG
- Import locally the entire polyDB dataset
- Publish the metadata in production
- Write exemplary SPARQL queries

**Checklist for this issue**: 
(Some checks for making sure this feature request is completely formulated)
- [ ] Participants in discussion have been invited as assignees 
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] The main MaRDI project has been assigned to this issue

**Comment by eloiferrer** [comment]
Initial importer structure merged in https://github.com/MaRDI4NFDI/docker-importer/pull/70

**Comment by eloiferrer** [comment]
Metadata imported, still need to add a poly DB identifier pointing to the source.

**Comment by eloiferrer** [comment]
PolyDB metadata available from: https://portal.mardi4nfdi.de/wiki/PolyDB
