### ISSUE TITLE
Overwrite __repr__ methods for MardiEntities

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#72]
**New feature description in words**:
I find the current implementation of __repr__ in BaseEntity.py confusing to get a quick overview of an entity. 
__repr__ should return:
* English/German label
* English/German description
* Key-value pairs for statements and qualifiers if present.
 
**TODOS**: 
-  Rewrite __repr__ in MardiEntities.py to implement the previous schema.

**Checklist for this issue**: 
(Some checks for making sure this feature request is completely formulated)
- [ ] Participants in discussion have been invited as assignees 
- [ ] All fields of the issue have been filled 
- [ ] Example fields have been removed
- [ ] The main MaRDI project has been assigned to this issue

**Comment by eloiferrer** [comment]
I think it would be nice to have, but not required at all.
