### ISSUE TITLE
Add polyDB ID in the polyDB importer

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#75]
**Issue description**:
The polyDB ID (https://portal.mardi4nfdi.de/wiki/Property:P1437) has been created manually and also manually added to the already existing polyDB collections.
The polyDB importer has to be modified to create this property during setup() and to add it to new collections automatically.
 
 
**TODOS**: 
- [ ] Add 'polyDB ID' with formatter URL in new_entities.json
- [ ] Add statement with wdt:'poly DB' for each new collection.

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.
