### ISSUE TITLE
polyDB updater

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#76]
**Issue description**:
Metadata on 21 polyDB collections has been inserted to the KG. 
The update functionality to overwrite existing entities with new information from polyDB.org and to create new collections has to be implemented. 
 
**TODOS**: 
- [ ] Implement update() function in polydb/collection.py

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.
