### ISSUE TITLE
Author disambiguator/synchronizer

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#77]
**Issue description**:
The current importers (CRAN, zbMath, polyDB) create entities for authors using ORCID ID, zbMath ID or no identifier. 
For the cases in which an identifier exists, authors might have been created more than once by different importers.
Duplicate authors should be identified, merged and completed with information from Wikidata.
The dataset mentioned here (https://github.com/MaRDI4NFDI/portal-compose/issues/344) can be useful for the task. 
 
**TODOS**: 
- [ ] For each author in the KG that has an ORCID or a zbMath ID, check that the author has not been created twice (if so, merge).
- [ ] Given an ID, assign other IDs to the authors if available in Wikidata or in the dataset.
- [ ] Merge duplicate entities.

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
The ORCID for all the zbmath authors in https://zenodo.org/records/7378860 have been inserted.

Current statistics in the KG:
- Humans = 1178288
- Humans with zbmath ID = 1117009
- Humans with ORCID ID = 40109

- Humans with zbmath ID and Wikidata = 40753
- Humans with zbmath ID and ORCID = 32619
- Humans with arXiv author ID = 127

Next step: get Wikidata QID for as many humans as possible:
- given the zbMath ID & given the ORCID ID

**Comment by eloiferrer** [comment]
I've imported further Wikidata QIDs given the current ORCID in the KG. 
I've also merge several authors that had the same ORCID ID. 

Current statistics:
- Humans = 1178923
- Humans with zbmath ID = 1117010
- Humans with ORCID ID = 41577
- Humans with zbmath ID and Wikidata = 54884
- Humans with zbmath ID and ORCID = 34331
- Humans with arXiv author ID = 140

**Comment by eloiferrer** [comment]
Wikidata has author items that contain two zbMath IDs. Most of the cases this is wrong, but it results in our knowledge graph having the same Wikidata QID for two different zbmath authors.
See cases here: http://tinyurl.com/27d65qov
This would require some manual disambiguation.
