### ISSUE TITLE
[Epic] Develop new importer strategy

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#83]
**Epic description in words**:

**Additional Info**:
 
- 
 
**Corresponding Milestones**: 
  
 - corresponding milestone one 
 
**Epic issues**: 
- [ ] Test Airflow, setup basic case.
- [ ] Define automatic update workflow.
- [ ] Setup Bot-users for each import source.
- [ ] API for the mapping SQL table.

**Related bugs**: 
  
- 

**Epic acceptance criteria**: 
  
- [ ] first criterion 

**Checklist for this epic**: 
- [ ] the main MaRDI project has been assigned as project
- [ ] report has been created
