### ISSUE TITLE
Fix python docstrings for sphinx

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/docker-importer#9]
**Issue description**:

sphinx assumes that python docstrings are written in [restructuredtext format](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html), which differs slightly from markdown. I quite like the google style for docstrings: https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
 
**TODOS**: 

- [ ] agree on docstring style
- [ ] adapt docstrings accordingly & be consistent in the future

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
