### ISSUE TITLE
Pull last version of WikibaseIntegrator in Dockerfile

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#94]
**Issue description**:
Update Dockerfile to install the last version of WikibaseIntegrator.
(Check that MardiImporter still works after that)
 
 
**TODOS**: 

- [ ] Delete lines 62-63 in Dockerfile

**Acceptance-Criteria** 

**Checklist for this issue**: 

- [ ] Assignee has been set for this issue 
- [ ] All fields of the issue have been filled 
- [ ] Issue has been assigned to the main project
- [ ] Code was merged
- [ ] Feature branch has been deleted and issues were updated / closed
- [ ] Issue is tracked by an epic, or the label 'non-epic' is set to the issue.

**Comment by eloiferrer** [comment]
This has been fixed in https://github.com/MaRDI4NFDI/docker-importer/pull/102
